### ISSUE TITLE
firezone:lastest crashing

### ISSUE THREAD

**Issue by JerboaGobi** [CloudFire-LLC/cloudfire#1054]
Hello,

I recently migrated to firezone/firezone:lastest as I was testing the docker image prior to .0.6.4. Since that migration I've been having some issues with the container crashing.

The container crashes on the POST request to:
/auth/identity/callback

I'm on ARM64 and running using Trafik as a reverse proxy.

```
version: '2.2'

networks:
  db_connection:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.139.33.8/29
  macvlan1109:
    external: true

services:
  firezone:
    #image: 358e32ad874c #base image
    # ee517d5cac8c - TCP dump
    image: firezone/firezone

    container_name: firezone

    volumes:
      # Persist private key through containers, the parent path to WIREGUARD_PRIVATE_KEY_PATH.
      - /var/docks/firezone/data/firezone:/var/firezone

    env_file:
      - ./.env

    labels:
      - traefik.enable=true
      - traefik-dmz.instance.enable=true

      - traefik.docker.network=macvlan1109

      - traefik.http.routers.firezone.rule=Host(`vpn.mydomain.com`)
      - traefik.http.routers.firezone.entrypoints=https
      - traefik.http.services.firezone.loadbalancer.server.port=4000
      - traefik.http.routers.firezone.tls=true
      - traefik.http.routers.firezone.tls.certresolver=letsencrypt

      - traefik.http.middlewares.security-headers.headers.accesscontrolallowmethods=GET, OPTIONS, PUT
      - traefik.http.middlewares.security-headers.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.security-headers.headers.addvaryheader=true
      - traefik.http.middlewares.security-headers.headers.hostsproxyheaders=X-Forwarded-Host
      - traefik.http.middlewares.security-headers.headers.sslredirect=true
      - traefik.http.middlewares.security-headers.headers.sslproxyheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.security-headers.headers.stsseconds=63072000
      - traefik.http.middlewares.security-headers.headers.stsincludesubdomains=true
      - traefik.http.middlewares.security-headers.headers.stspreload=true
      - traefik.http.middlewares.security-headers.headers.forcestsheader=true
      - traefik.http.middlewares.security-headers.headers.framedeny=true
      - traefik.http.middlewares.security-headers.headers.contenttypenosniff=true
      - traefik.http.middlewares.security-headers.headers.browserxssfilter=true
      - traefik.http.middlewares.security-headers.headers.referrerpolicy=same-origin
      - "traefik.http.middlewares.security-headers.headers.featurepolicy=camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
      - traefik.http.middlewares.security-headers.headers.frameDeny=true
      - traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true
      - "traefik.http.middlewares.security-headers.headers.permissionsPolicy=accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
      - "traefik.http.middlewares.security-headers.headers.customresponseheaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex"


      - traefik.http.middlewares.firezone-header-connection.headers.customresponseheaders.Connection=upgrade
      - traefik.http.middlewares.firezone-header-upgrade.headers.customresponseheaders.Upgrade=websocket


        #Applying middlewares
      - traefik.http.routers.firezone.middlewares=security-headers,firezone-header-connection,firezone-header-upgrade

    restart: always

    cpus: 1.00
    cpu_shares: 26
    mem_limit: 128M
    pids_limit: 100

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    security_opt:
      - no-new-privileges:true

    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
            #- net.ipv4.ip_forward=1
            #- net.ipv6.conf.all.forwarding=1
            #- net.ipv4.conf.all.proxy_arp=1

    networks:
      db_connection:
        ipv4_address: 172.139.33.10
      macvlan1109:
        ipv4_address: 172.25.139.248

    dns:
      - 172.25.139.254

  postgres:

    image: postgres:15

    container_name: firezone_postgres

    volumes:
      - /var/docks/firezone/data/postgres:/var/lib/postgresql/data

    env_file:
      - ./.env

    restart: always

    cpus: 1.00
    cpu_shares: 26
    mem_limit: 128M
    pids_limit: 100

    security_opt:
      - no-new-privileges:true

    networks:

      db_connection:
        ipv4_address: 172.139.33.11
```

```
EXTERNAL_URL=https://vpn.mydomain.com
ADMIN_EMAIL=
DEFAULT_ADMIN_PASSWORD=
GUARDIAN_SECRET_KEY=
SECRET_KEY_BASE=
LIVE_VIEW_SIGNING_SALT=
COOKIE_SIGNING_SALT=
COOKIE_ENCRYPTION_SALT=
DATABASE_ENCRYPTION_KEY=
DATABASE_PASSWORD=


## Web
PHOENIX_PORT=4000
##Cloudflare & Traefik Proxies
EXTERNAL_TRUST_PROXIES=[{"173.245.48.0/20":"103.21.244.0/22"},{"173.245.48.0/20":"103.22.200.0/22"},{"173.245.48.0/20":"103.31.4.0/22"},{"173.245.48.0/20":"141.101.64.0/18"},{"173.245.48.0/20":"108.162.192.0/18"},{"173.245.48.0/20":"190.93.240.0/20"},{"173.245.48.0/20":"188.114.96.0/20"},{"173.245.48.0/20":"197.234.240.0/22"},{"173.245.48.0/20":"198.41.128.0/17"},{"173.245.48.0/20":"162.158.0.0/15"},{"173.245.48.0/20":"104.16.0.0/13"},{"173.245.48.0/20":"104.24.0.0/14"},{"173.245.48.0/20":"172.64.0.0/13"},{"173.245.48.0/20":"131.0.72.0/22"},{"173.245.48.0/20:"172.25.139.253/32""}]

## External
WIREGUARD_ALLOWED_IPS=172.50.50.0/24
WIREGUARD_IPV4_MASQUERADE=false


## DB
DATABASE_HOST=172.139.33.11

## App
ALLOW_UNPRIVILEGED_DEVICE_MANAGEMENT=false
ALLOW_UNPRIVILEGED_DEVICE_CONFIGURATION=false
```

I've deleted the images, containers, and clearing the bind directories thinking maybe something was leftover from previous deployments to no avail. I haven't been able to locate any logs which indicate what the issue might be. If there's a procedure for enabling debug logs that would be helpful. Any insights you may have would prove to be helpful. 

Thank you.
