### ISSUE TITLE
Network and Caddy has complex problems

### ISSUE THREAD

**Issue by hidekuro** [CloudFire-LLC/cloudfire#1100]
In 0.6.6, The `firezone` and `postgres` services has belongs to network that named `firezone-network`.
But `caddy` service is not. Therefore, the hostname `firezone` cannot be resolved from `caddy` service containers.

Otherwise, `networks` and `network_mode: host` will conflicts each other. so we need to rollback to bridge mode and binding host ports.

Next, The "site address" in Caddyfile should be contains the domain or IP address to enable to "Automatic HTTPS" [^1] feature.

[^1]:https://caddyserver.com/docs/automatic-https#activation

I believe following service definition patch will resolves above problems.

```diff
diff --git a/docker-compose.prod.yml b/docker-compose.prod.yml
index f7c42490..7c09738a 100644
--- a/docker-compose.prod.yml
+++ b/docker-compose.prod.yml
@@ -20,6 +20,9 @@ version: '3.7'
 services:
   caddy:
     image: caddy:2
+    ports:
+      - 80:80
+      - 443:443
     volumes:
       - ${FZ_INSTALL_DIR:-.}/caddy:/data/caddy
     # See Caddy's documentation for customizing this line
@@ -29,14 +32,14 @@ services:
       - -c
       - |
         cat <<EOF > /etc/caddy/Caddyfile && caddy run --config /etc/caddy/Caddyfile
-
-        https:// {
+        ${EXTERNAL_URL:-} {
           log
           reverse_proxy * firezone:13000
           ${TLS_OPTS:-}
         }
         EOF
-    network_mode: "host"
+    networks:
+      firezone-network:
     deploy:
       <<: *default-deploy
```

Currently, I avoiding this problem with following `docker-compose.override.yml`.

```yaml
services:
  firezone:
    image: firezone/firezone:0.6.6
  # workarounds
  caddy:
    ports:
      - 80:80
      - 443:443
    networks:
      firezone-network:
    network_mode: bridge
    command: caddy reverse-proxy --to firezone:13000 --from ${EXTERNAL_URL}
```
