### ISSUE TITLE
No internet for ipv6 tunnel

### ISSUE THREAD

**Issue by loicy** [CloudFire-LLC/cloudfire#1202]
Hello,

I am currently testing firezone.

I used your automatic script. It works correctly in ipv4. Firezone also gives an internal ipv6 but on exit, nothing goes through the ipv6.

The goal is that when I don't have an ipv4, I get an ipv6, it's boring ;p

The docker compose has not been modified but here is the docker compose :

```
-deploy: &default-deploy
  restart_policy:
    condition: unless-stopped
    delay: 5s
    window: 120s
  update_config:
    order: start-first

version: '3.7'

services:
  caddy:
    image: caddy:2
    volumes:
      - ${FZ_INSTALL_DIR:-.}/caddy:/data/caddy
    # See Caddy's documentation for customizing this line
    # https://caddyserver.com/docs/quick-starts/reverse-proxy
    command:
      - /bin/sh
      - -c
      - |
        cat <<EOF > /etc/caddy/Caddyfile && caddy run --config /etc/caddy/Caddyfile

        https:// {
          log
          reverse_proxy * 172.25.0.100:13000
          ${TLS_OPTS:-}
        }
        EOF
    network_mode: "host"
    deploy:
      <<: *default-deploy

  firezone:
    image: firezone/firezone
    ports:
      - 51820:51820/udp
    env_file:
      # This should contain a list of env vars for configuring Firezone.
      # See https://docs.firezone.dev/reference/env-vars for more info.
      - ${FZ_INSTALL_DIR:-.}/.env
    volumes:
      # IMPORTANT: Persists WireGuard private key and other data. If
      # /var/firezone/private_key exists when Firezone starts, it is
      # used as the WireGuard private. Otherwise, one is generated.
      - ${FZ_INSTALL_DIR:-.}/firezone:/var/firezone
    cap_add:
      # Needed for WireGuard and firewall support.
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      # Needed for masquerading and NAT.
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - postgres
    networks:
      firezone-network:
        ipv4_address: 172.25.0.100
    deploy:
      <<: *default-deploy

  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-firezone}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}
    networks:
      - firezone-network
    deploy:
      <<: *default-deploy
      update_config:
        order: stop-first

# Postgres needs a named volume to prevent perms issues on non-linux platforms
volumes:
  postgres-data:

networks:
  firezone-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
```

Nft list ruleset

```
table inet filter {
        chain input {
                type filter hook input priority filter; policy accept;
        }

        chain forward {
                type filter hook forward priority filter; policy accept;
        }

        chain output {
                type filter hook output priority filter; policy accept;
        }
}
table ip nat {
        chain DOCKER {
                iifname "docker0" counter packets 0 bytes 0 return
                iifname "br-683eae7cefd5" counter packets 0 bytes 0 return
                iifname != "br-683eae7cefd5" meta l4proto udp udp dport 51820 counter packets 7 bytes 984 dnat to 172.25.0.100:51820
        }

        chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                oifname != "docker0" ip saddr 172.17.0.0/16 counter packets 0 bytes 0 masquerade 
                oifname != "br-683eae7cefd5" ip saddr 172.25.0.0/16 counter packets 3174 bytes 265815 masquerade 
                meta l4proto udp ip saddr 172.25.0.100 ip daddr 172.25.0.100 udp dport 51820 counter packets 0 bytes 0 masquerade 
        }

        chain PREROUTING {
                type nat hook prerouting priority dstnat; policy accept;
                fib daddr type local counter packets 10074 bytes 398548 jump DOCKER
        }

        chain OUTPUT {
                type nat hook output priority -100; policy accept;
                ip daddr != 127.0.0.0/8 fib daddr type local counter packets 0 bytes 0 jump DOCKER
        }
}
table ip filter {
        chain DOCKER {
                iifname != "br-683eae7cefd5" oifname "br-683eae7cefd5" meta l4proto udp ip daddr 172.25.0.100 udp dport 51820 counter packets 12 bytes 2072 accept
        }

        chain DOCKER-ISOLATION-STAGE-1 {
                iifname "docker0" oifname != "docker0" counter packets 0 bytes 0 jump DOCKER-ISOLATION-STAGE-2
                iifname "br-683eae7cefd5" oifname != "br-683eae7cefd5" counter packets 300168 bytes 217438302 jump DOCKER-ISOLATION-STAGE-2
        }

        chain DOCKER-ISOLATION-STAGE-2 {
                oifname "docker0" counter packets 0 bytes 0 drop
                oifname "br-683eae7cefd5" counter packets 0 bytes 0 drop
                counter packets 300168 bytes 217438302 return
        }

        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                counter packets 918818 bytes 451519073 jump DOCKER-USER
                counter packets 918818 bytes 451519073 jump DOCKER-ISOLATION-STAGE-1
                oifname "docker0" ct state related,established counter packets 0 bytes 0 accept
                oifname "docker0" counter packets 0 bytes 0 jump DOCKER
                iifname "docker0" oifname != "docker0" counter packets 0 bytes 0 accept
                iifname "docker0" oifname "docker0" counter packets 0 bytes 0 accept
                oifname "br-683eae7cefd5" ct state related,established counter packets 618449 bytes 234049843 accept
                oifname "br-683eae7cefd5" counter packets 201 bytes 30928 jump DOCKER
                iifname "br-683eae7cefd5" oifname != "br-683eae7cefd5" counter packets 300168 bytes 217438302 accept
                iifname "br-683eae7cefd5" oifname "br-683eae7cefd5" counter packets 39 bytes 2340 accept
        }

        chain DOCKER-USER {
                counter packets 918818 bytes 451519073 return
        }
}
table ip6 nat {
        chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                oifname "eth0" counter packets 2 bytes 120 masquerade   //add by me
        }
}
```

Any idea ? ;p
