### ISSUE TITLE
Docker compose Gateway deployment

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3041]
Customer contributed a sample working `docker-compose.yml` to deploy a gateway.

- [ ] Add relevant docs
- [ ] Add upgrade docs
- [ ] Add relevant deployment instructions in portal

```yaml
version: '3.7'

services:
  firezone-gateway:
    image: ghcr.io/firezone/gateway:1
    environment:
      - FIREZONE_ID=<id>
      - FIREZONE_TOKEN=<token>
      - RUST_LOG=str0m=warn,info
      - FIREZONE_ENABLE_MASQUERADE=1
      - FIREZONE_NAME=<name-of-gateway>
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    healthcheck:
      test: ["CMD", "ip", "link", "|", "grep", "tun-firezone"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 1m
    devices:
      - /dev/net/tun:/dev/net/tun
```
