### ISSUE TITLE
Docker for Mac drops UDP traffic if source port is reused after 120s idle period

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#7818]
Opening a separate tracking issue to further investigate the issue seen in https://github.com/firezone/firezone/issues/7763#issuecomment-2600952926.

**Comment by jamilbk** [comment]
Ok, this is starting to get interesting. Here are the debugging steps I tried (without success):

- Deleting the `fwmark` rule we add in `tun_device_manager::linux` in case this is somehow affecting things
- Capturing a pcap of the host interface -> No requests seen
- Capturing a pcap of the `eth0` interface from _another_ Docker container -> Requests seen, no replies seen

And lo and behold, this issue seems to be completely resolved by #7819!

My new working theory is that the conntracking logic in either the Docker NAT implementation or the macOS kernel's virtualization framework requires some sort of "cooling off period" where a particular source address:port cannot be reused after its NAT binding has expired.

To test this, I've created a minimally reproducible compose file that highlights the issue using plain ol' DNS:


```yaml
services:
  kdig:
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        # kdig supports bind address and port
        apk add -u cmd:kdig

        # Pick a random source port
        source_port=$(shuf -i 60000-61000 -n 1)
        echo
        echo "Source port: $$source_port"
        echo

        # Perform query, creating NAT binding
        kdig -b 0.0.0.0:$$source_port @1.1.1.1 google.com

        # Wait for 5 minutes
        echo
        echo "Sleeping for 5 minutes..."
        sleep 300

        # Query again, fails
        echo
        kdig @1.1.1.1 -b 0.0.0.0:$$source_port google.com

```

And output:

```
jamil@Airbook-Mac:~/tmp/docker-nat-rebinding % docker compose up
[+] Running 1/1
 ✔ Container docker-nat-rebinding-kdig-1  Recreated                                                                                                                                                                                                                                                                                                                               0.1s
Attaching to kdig-1
kdig-1  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/main/aarch64/APKINDEX.tar.gz
kdig-1  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/community/aarch64/APKINDEX.tar.gz
kdig-1  | (1/18) Installing gmp (6.3.0-r2)
kdig-1  | (2/18) Installing nettle (3.10-r1)
kdig-1  | (3/18) Installing libunistring (1.2-r0)
kdig-1  | (4/18) Installing libidn2 (2.3.7-r0)
kdig-1  | (5/18) Installing libffi (3.4.6-r0)
kdig-1  | (6/18) Installing libtasn1 (4.19.0-r2)
kdig-1  | (7/18) Installing p11-kit (0.25.5-r2)
kdig-1  | (8/18) Installing gnutls (3.8.8-r0)
kdig-1  | (9/18) Installing lmdb (0.9.33-r0)
kdig-1  | (10/18) Installing ngtcp2 (1.9.1-r0)
kdig-1  | (11/18) Installing ngtcp2-gnutls (1.9.1-r0)
kdig-1  | (12/18) Installing knot-libs (3.4.3-r0)
kdig-1  | (13/18) Installing ncurses-terminfo-base (6.5_p20241006-r3)
kdig-1  | (14/18) Installing libncursesw (6.5_p20241006-r3)
kdig-1  | (15/18) Installing libedit (20240808.3.1-r0)
kdig-1  | (16/18) Installing nghttp2-libs (1.64.0-r0)
kdig-1  | (17/18) Installing userspace-rcu (0.14.1-r1)
kdig-1  | (18/18) Installing knot-utils (3.4.3-r0)
kdig-1  | Executing busybox-1.37.0-r9.trigger
kdig-1  | OK: 20 MiB in 33 packages
kdig-1  |
kdig-1  | Source port: 60716
kdig-1  |
kdig-1  | ;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 2823
kdig-1  | ;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 1
kdig-1  |
kdig-1  | ;; EDNS PSEUDOSECTION:
kdig-1  | ;; Version: 0; flags: ; UDP size: 1232 B; ext-rcode: NOERROR
kdig-1  |
kdig-1  | ;; QUESTION SECTION:
kdig-1  | ;; google.com.                        IN      A
kdig-1  |
kdig-1  | ;; ANSWER SECTION:
kdig-1  | google.com.           139     IN      A       142.251.32.46
kdig-1  |
kdig-1  | ;; Received 55 B
kdig-1  | ;; Time 2025-01-21 17:59:07 UTC
kdig-1  | ;; From 1.1.1.1@53(UDP) in 9.6 ms
kdig-1  |
kdig-1  | Sleeping for 5 minutes...
kdig-1  |
kdig-1  | ;; WARNING: response timeout for 1.1.1.1@53(UDP)
kdig-1  | ;; WARNING: response timeout for 1.1.1.1@53(UDP)
kdig-1  | ;; WARNING: response timeout for 1.1.1.1@53(UDP)
kdig-1  | ;; ERROR: failed to query server 1.1.1.1@53(UDP)
```

Going to do a bit more investigation and then I'll open an issue somewhere upstream if this is determined to deviate from expected behavior. I would suspect the bug lies in Docker's NAT implementation and more specifically how it sets up conntrack rules (if any).
